[ticket_m]
title = "티켓링크 모바일"
url = "http://m.ticketlink.co.kr/help/notice"
entrySelector = "#detail_content > li"
titleSelector = "h3"
linkSelector = "a"
contentSelector = "a > dl > dd:nth-child(2)"
